# Environment settings
seed: 1234
state: 'INFO'

# Data settings
data_path: '/home/kyubyungchae/recbole/Data'
dataset: 'rovigos'
USER_ID_FIELD: 'user_id'
ITEM_ID_FIELD: 'item_id'
# RATING_FIELD: "rating"
TIME_FIELD: 'timestamp'
load_col:
  inter: [user_id, item_id, timestamp]
  user: [user_id, age, type]
  item: [item_id, price, class]

MAX_ITEM_LIST_LENGTH: 50


# model config
# embedding_size: 64
# hidden_size: 128
# num_layers: 1
dropout_prob: 0.3
# loss_type: 'CE'


user_inter_num_interval: '[5,inf)'
item_inter_num_interval: '[5,inf)'


# For S3Rec
embedding_size: 10
item_attribute: 'class'
loss_type: 'BPR'
train_neg_sample_args: 
  uniform: 1


# Training settings
epochs: 100
train_batch_size: 128
learner: 'adam'
learning_rate: 0.001
weight_decay: 0.0
# train_neg_sample_args: ~  
eval_step: 1
stopping_step: 10
weight_decay: 0.0





# Evaluation settings
eval_batch_size: 128
eval_args:
    group_by: user
    order: TO
    # split: {'LS': 'valid_and_test'}
    split: {'RS': [0.8,0.1,0.1]}
    mode: 'full' # modified /home/kwangeunyeo/anaconda/envs/py38/lib/python3.8/site-packages/recbole/sampler/sampler.py
# metrics: ['AUC', 'GAUC', 'Hit', 'NDCG', 'LogLoss', 'MRR']
metrics: ['Hit', 'NDCG', 'MRR']

topk: [1, 5, 10]
valid_metric: NDCG@10
metric_decimal_place: 4